## Basic Configuration
baseurl = "https://easystats.github.io/blog/"
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"
relativeURLs = true
enableEmoji = true

title = "easystats"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
googleAnalytics = "UA-97457476-9"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Dominique Makowski and Daniel Lüdecke"
    title = "easystats"
    # description = "..."
    authorimage = "/img/logo.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "easystats"
    license = "GPL-3.0"
    licenseURL = "https://github.com/easystats/easystats"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "easystats/easystats"
    # instagram = "<username>"
    # xing = "<username>"
    # linkedin = "<username>"
    # twitter = "<username>"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    # telegram = "<username>"
    # email = "your-email@example.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "portfolio"
    weight = 200
    url = "/portfolio/"
[[menu.main]]
    name = "Ressources"
    identifier = "ressources"
    weight = 200
    url = "/ressources/"
