---
title: "New features in the parameters package"
author: "easystats"
date: 2020-10-13
categories: ["R", "parameters"]
tags: ["R", "easystats", "parameters"]
---


```{r message=FALSE, warning=FALSE, include=FALSE}
library(knitr)
options(knitr.kable.NA = '',
        digits=2,
        dpi=450)
```

## New supported models in the parameters package

You probably already have heard of the [*parameters* package](https://easystats.github.io/parameters/), a light-weight package to extract, compute and explore the parameters of statistical models using R (if not, there is a related [publication](https://joss.theoj.org/papers/10.21105/joss.02445) introducing the package's main features).



## Get Involved

*easystats* is a new project in active development, looking for contributors and supporters. Thus, do not hesitate to contact us if **you want to get involved :)**

- **Check out our other blog posts** [***here***](https://easystats.github.io/blog/posts/)!

## Stay tuned 

To be updated about the *upcoming features* and cool R or data science stuff, you can **follow the packages on GitHub** (click on one [of the easystats package](https://github.com/easystats)) and then on the **Watch** button on the top right corner) as well as the **easystats team on twitter and online**:

- [\@easystats4u](https://twitter.com/easystats4u)
- [\@strengejacke](https://twitter.com/strengejacke)
- [\@DominiqueMakowski](https://twitter.com/Dom_Makowski)
- [\@mattansb](https://twitter.com/mattansb)
- [\@IndrajeetPatil](https://twitter.com/patilindrajeets)
- [\@humanfactors](https://twitter.com/humanfactorsio)
- [\@lindeloev](https://twitter.com/jonaslindeloev)
- [\@jacob-long](https://twitter.com/jacobandrewlong)
- [\@pdwaggoner](https://pdwaggoner.github.io/)
- [\@LeoDutriaux](https://twitter.com/LDtrx)
