---
title: "Check your (Mixed) Model for Multicollinearity with 'performance'"
author: "easystats"
date: 2019-06-06
categories: ["R", "performance"]
tags: ["R", "easystats", "performance", "multicollinearity"]
---


```{r message=FALSE, warning=FALSE, include=FALSE}
library(knitr)
options(knitr.kable.NA = '',
        digits = 3,
        dpi = 450)

library(performance)
library(glmmTMB)
library(see)
```




```{r message=FALSE, warning=FALSE}
library(performance)

# fit model
data(mtcars)
model <- lm(mpg ~ wt + cyl + gear + disp, data = mtcars)

# now check for multicollinearity
check_collinearity(model)

# plot results
x <- check_collinearity(model)
plot(x)
```

```{r}
library(glmmTMB)
data(Salamanders)

# create highly correlated pseudo-variable
set.seed(1)
Salamanders$cover2 <-
  Salamanders$cover * runif(n = nrow(Salamanders), min = .9, max = 1.1)

# fit mixed model with zero-inflation
model <- glmmTMB(
  count ~ spp + mined + cover + cover2 + (1 | site), 
  ziformula = ~ spp + mined, 
  family = truncated_poisson, 
  data = Salamanders
)

# now check for multicollinearity
check_collinearity(model)
```

```{r}
plot(check_collinearity(model))
```

## join easystats

Note that [***easystats***](https://github.com/easystats) is a new project in active development, and feedback, suggestions, comments are very welcome! Do not hesitate to contact us if **you want to get involved :)**

- **Check out our other blog posts** [***here***](https://easystats.github.io/blog/posts/)!

